### ISSUE TITLE
Documentation dark theme

### ISSUE THREAD

**Issue by katsaii** [katsaii/catspeak-lang#102]
### What is your feature request?

Add a dark theme to the docs.

### Please describe in detail how you expect this new feature to behave.

Use these colours (or colours close to these):
```css
:root {
  --darkreader-bg--c-bg: #1b1e1f;
  --darkreader-bg--c-bg-dark: #232627;
  --darkreader-text--c-fg: #d3cfc9;
  --darkreader-text--c-fg-light: #c8c3bc;
  --darkreader-border--c-fg-light: #3e4346;
  --darkreader-text--c-fg-2: #aea79c;
  --darkreader-text--c-accent: #34a4ff;
}
```
